-- characters inserts

INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (1, 'Goku', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (2, 'Goku', 4, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (3, 'Gohan (Kid)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (4, 'Gohan (Kid)', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (5, 'Piccolo', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (6, 'Krillin', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (7, 'Krillin', 5, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (8, 'Yamcha', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (9, 'Tien', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (10, 'Chiaotzu', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (11, 'Raditz', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (12, 'Saibaman', 4, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (13, 'Nappa', 1, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (14, 'Nappa', 4, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (15, 'Vegeta', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (16, 'Goku', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (17, 'Super Saiyan Goku', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (18, 'Fused with Nail Piccolo', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (19, 'Vegeta', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (20, 'Vegeta', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (21, 'Zarbon', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (22, 'Dodoria', 1, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (23, 'Guldo', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (24, 'Burter', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (25, 'Recoome', 1, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (26, 'Jeice', 5, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (27, 'Captain Ginyu', 1, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (28, 'Captain Ginyu', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (29, '1st Form Frieza', 2, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (30, '1st Form Frieza', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (31, '2nd Form Frieza', 1, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (32, '3rd Form Frieza', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (33, 'Final Form Frieza', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (34, 'Mercenary Tao', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (35, 'Pikkon', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (36, 'Pikkon', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (37, 'Jaco', 1, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (38, 'Final Form Frost', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (39, 'Pan', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (40, 'Pan', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (41, 'Fused with Nail Piccolo', 1, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (42, 'Yamcha', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (43, 'Tien', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (44, 'Chiaotzu', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (45, 'Final Form Frost', 4, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (46, 'Super Saiyan Goku', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (47, 'Super Saiyan Vegeta', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (48, 'Super Saiyan Trunks (Teen)', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (49, 'Android #20', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (50, 'Android #19', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (51, 'Turles', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (52, 'Mai', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (53, 'Trunks (Teen)', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (54, 'Vegeta', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (55, 'Turles', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (56, 'Android #20', 5, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (57, 'Android #19', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (58, 'Yamcha', 4, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (59, 'Saibaman', 5, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (60, 'Jaco', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (61, 'Super Saiyan Goku', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (62, 'Krillin', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (63, 'Android #17', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (64, 'Android #18', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (65, '1st Form Cell', 4, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (66, 'Master Roshi', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (67, 'Super Saiyan Cabba', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (68, 'Android #18', 3, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (69, 'Cabba', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (70, 'Master Roshi', 4, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (71, 'Android #17', 1, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (72, 'Goku', 5, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (73, '1st Form Cell', 5, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (74, 'Super Saiyan Goku', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (75, 'Goku (Youth)', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (76, 'Super Saiyan Vegeta', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (77, 'Bardock', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (78, 'Demon King Piccolo', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (79, 'Legendary Super Saiyan Broly', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (80, '1st Form Frieza', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (81, 'Super Saiyan Goku', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (82, 'Trunks', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (83, 'Demon King Piccolo', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (84, 'Pan', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (85, '1st Form Frieza', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (86, 'Bardock', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (87, 'Raditz', 2, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (88, 'Zarbon', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (89, 'Dodoria', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (90, 'Super Vegeta', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (91, 'Fused with Kami Piccolo', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (92, 'Android #16', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (93, '2nd Form Cell', 2, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (94, 'Cooler', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (95, 'Thouser', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (96, 'Cooler', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (97, 'Super Saiyan Goku', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (98, 'Trunks (Kid)', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (99, 'Goten (Kid)', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (100, 'Perfect Form Cell', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (101, 'Thouser', 1, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (102, 'Android #16', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (103, 'Android #18', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (104, 'Perfect Form Cell', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (105, 'Super Trunks', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (106, 'Cell Jr.', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (107, 'Super Saiyan 2 Gohan (Youth)', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (108, 'Super Saiyan 3 Goku', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (109, 'Majin Buu: Good', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (110, 'Super Saiyan Goku', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (111, 'World Champion Hercule', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (112, 'Majin Buu: Good', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (113, 'Gohan (Youth)', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (114, 'Cell Jr.', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (115, 'Turles', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (116, 'Super Saiyan Goku', 5, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (117, 'Krillin', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (118, 'Super Saiyan Gohan', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (119, 'Super Saiyan 2 Trunks (Adult)', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (120, 'Goku', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (121, 'Goku Black', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (122, 'Zamasu', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (123, 'Super Saiyan Kale (Berserk)', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (124, 'Mai', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (125, 'Goku Black', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (126, 'Vegeta', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (127, 'Zamasu', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (128, 'Android #17', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (129, 'Android #18', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (130, 'Vegeta', 4, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (131, '2nd Form Cell', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (132, 'Vegito', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (133, 'Super Saiyan Trunks (Kid)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (134, 'Super Saiyan Goten (Kid)', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (135, 'Majin Vegeta', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (136, 'Super Saiyan Gotenks', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (137, 'King of the Demon Realm Dabura', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (138, 'King of the Demon Realm Dabura', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (139, 'Broly: Fury', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (140, 'Super Gogeta', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (141, 'Super Janemba', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (142, 'Super Saiyan 2 Goku', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (143, 'Super Saiyan Bardock', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (144, 'Chilled', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (145, 'Super Saiyan Trunks (Teen)', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (146, 'Pan: Honey', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (147, 'Super Saiyan Vegeta', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (148, 'Super Saiyan Gohan (Teen)', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (149, 'Fasha', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (150, 'Tora', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (151, 'Goku', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (152, 'Cabba', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (153, 'Nappa (Young)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (154, 'Nappa', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (155, 'Super Saiyan Broly', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (156, 'Super Saiyan God Goku', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (157, 'God of Destruction Beerus', 3, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (158, 'Boujack', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (159, 'Final Form Cooler', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (160, 'Trunks (Youth)', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (161, 'Whis', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (162, 'Gohan', 3, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (163, 'Super Saiyan 2 Caulifla', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (164, 'Ribrianne', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (165, 'Chi-Chi', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (166, 'Bulma (Youth)', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (167, 'Videl', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (168, 'Launch', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (169, 'Caulifla', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (170, 'Kakunsa', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (171, 'Rozie', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (172, 'Chi-Chi', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (173, 'Videl', 1, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (174, 'Great Saiyaman 1', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (175, 'Great Saiyaman 2', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (176, 'Super Saiyan God Vegeta', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (177, 'Ultimate Gohan', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (178, 'Super Saiyan 3 Goku', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (179, 'Super Saiyan 2 Vegeta', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (180, 'Super Namekian Lord Slug', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (181, 'Perfect Cell', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (182, 'Super Saiyan 2 Gohan (Youth)', 1, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (183, 'Gogeta', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (184, 'Gotenks', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (185, 'Trunks (Teen)', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (186, 'Tien', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (187, 'Majin Buu: Pure Evil', 2, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (188, 'Super Saiyan Vegeta', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (189, 'Hyper Meta-Rilldo', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (190, 'Super Saiyan 3 Gotenks', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (191, 'Buu: Super', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (192, 'Taitans Yamcha', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (193, 'Super Namekian Lord Slug', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (194, 'Bulma (Youth)', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (195, 'Super Saiyan Goten (Kid)', 5, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (196, 'Super Saiyan Gohan (Teen)', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (197, 'Super Saiyan Goku', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (198, 'Legendary Super Saiyan Broly', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (199, 'Metal Cooler', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (200, 'Zangya', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (201, 'Videl', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (202, 'World Champion Hercule', 2, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (203, 'Fused with Kami Piccolo', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (204, 'Boujack', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (205, 'Ultimate Gohan Absorbed Buu: Super', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (206, 'Super Saiyan God SS Goku', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (207, 'Super Saiyan God SS Vegeta', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (208, 'Golden Frieza', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (209, 'Final Form Frieza: Full Power', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (210, 'Goku', 2, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (211, 'Super Janemba', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (212, 'Chilled', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (213, 'God of Destruction Beerus', 4, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (214, 'Super Vegito', 5, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (215, 'Buu: Kid', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (216, 'Trunks (Teen)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (217, 'Android #13', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (218, 'Android #14', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (219, 'Android #15', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (220, 'Vados', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (221, 'Guldo', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (222, 'Burter', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (223, 'Recoome', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (224, 'Jeice', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (225, 'Captain Ginyu', 5, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (226, 'Super Saiyan God SS Goku', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (227, 'Hit', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (228, 'Super Saiyan Gohan (Youth)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (229, 'Goku', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (230, 'Super #17', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (231, 'Fusion Android #13', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (232, 'Goku', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (233, 'Android #18', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (234, 'Bunny Girl Bulma (Youth)', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (235, 'Goku Captain Ginyu', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (236, 'Gohan (Kid)', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (237, 'Krillin', 5, 3, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (238, 'Nail', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (239, 'Nail', 3, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (240, 'Super Saiyan 3 Goku', 3, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (241, 'Goku', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (242, 'Piccolo', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (243, 'God of Destruction Champa', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (244, 'Bardock', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (245, 'Full Power Boujack', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (246, 'Vegeta', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (247, 'Gohan', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (248, 'Raditz', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (249, 'Ultimate Gohan Absorbed Buu: Super', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (250, 'Buu: Kid', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (251, 'Legendary Super Saiyan Broly', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (252, 'Android #13', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (253, 'Super Saiyan Rosé Goku Black', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (254, 'Super Saiyan God SS Vegeta', 3, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (255, 'Cooler', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (256, 'Final Form Frieza', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (257, 'Shisami', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (258, 'Super Saiyan 4 Goku', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (259, 'Super Saiyan 4 Vegeta', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (260, 'Nuova Shenron', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (261, 'Syn Shenron', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (262, 'Eis Shenron', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (263, 'Hero Tapion', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (264, 'Broly: Cheelai (Assist)', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (265, 'Kakarot Goku', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (266, 'Buu: Super', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (267, 'Goku', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (268, 'Trunks (Kid)', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (269, '2nd Form Frieza', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (270, 'Super Trunks', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (271, 'Hyper Meta-Rilldo', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (272, 'Super Saiyan God SS Gogeta', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (273, 'Super Saiyan God Goku', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (274, 'Super Saiyan Vegeta', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (275, 'Super Gogeta', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (276, 'Super Janemba', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (277, 'Super Baby 2', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (278, 'Android #14', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (279, 'Android #15', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (280, 'Super Saiyan 2 Kefla', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (281, 'Super Saiyan Trunks (Teen)', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (282, '1st Form Cell', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (283, 'Baby Vegeta', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (284, 'Android #21', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (285, 'Android #21: Evil', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (286, 'Android #21', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (287, 'Android #21: Good', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (288, 'Basil', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (289, 'Bergamo', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (290, 'Lavender', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (291, '1st Form Frieza', 5, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (292, 'Bardock', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (293, 'Vegito', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (294, 'Shugesh', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (295, 'Borgos', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (296, 'Mercenary Tao', 4, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (297, 'Super Kaioken Goku', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (298, 'Pikkon', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (299, 'Kale', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (300, 'Super Saiyan Gotenks', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (301, 'Super Saiyan God SS Goku', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (302, 'Super Saiyan God SS Vegeta', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (303, 'Goku (Youth)', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (304, 'Hit', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (305, 'Super Saiyan God SS Vegito', 2, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (306, 'Super Saiyan Trunks (Adult) (Rage)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (307, 'Fusion Zamasu', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (308, 'Omega Shenron', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (309, 'Super Full Power Saiyan 4 Goku', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (310, 'Syn Shenron', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (311, 'Gogeta', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (312, 'Super Vegeta', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (313, 'Gohan (Adult)', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (314, 'Gotenks Absorbed Buu: Super', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (315, 'Wasteland Bandit Yamcha', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (316, 'Tien', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (317, 'Krillin', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (318, 'Yamcha', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (319, 'Bido', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (320, 'Bujin', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (321, 'Gokua', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (322, 'Hit', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (323, 'Turles', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (324, 'Super Saiyan Goku', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (325, 'Jiren', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (326, 'Toppo', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (327, 'Dyspo', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (328, 'Goten (Kid)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (329, 'Trunks (Kid)', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (330, 'Perfect Form Cell', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (331, 'Vegeta', 2, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (332, 'Super Saiyan 2 Goku', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (333, 'Videl', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (334, 'Great Saiyaman 1 & 2 (Assist)', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (335, 'Goku Black', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (336, 'Ribrianne', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (337, 'Kakunsa', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (338, 'Rozie', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (339, 'Gohan (Kid)', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (340, 'Yurin', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (341, 'Super Saiyan Vegeta', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (342, 'Metal Cooler', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (343, 'Full Power Boujack', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (344, 'Ultra Instinct -Sign- Goku', 5, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (345, 'Final Form Frieza', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (346, 'Super Saiyan Broly: Full Power', 2, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (347, 'Final Form Frieza', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (348, 'Broly', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (349, 'Vegeta', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (350, 'Goku', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (351, 'Super Saiyan Gohan', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (352, 'Master Roshi', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (353, 'Buu: Kid', 2, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (354, 'Vegeta', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (355, 'Bulma (Youth)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (356, 'Super Saiyan Broly', 4, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (357, 'Demon King Piccolo (Aged)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (358, 'Trunks (Youth)', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (359, 'Super Saiyan Rosé Goku Black', 5, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (360, 'Trunks: Mai (Assist)', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (361, 'Super Saiyan Goku', 1, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (362, 'Super Saiyan God SS Goku', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (363, 'Goku Black', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (364, 'Super Saiyan 4 Goku', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (365, 'Android #18', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (366, 'Android #17', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (367, 'Baby Vegeta', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (368, 'Super Saiyan 4 Gogeta', 3, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (369, 'Super #17', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (370, 'Super Baby 2', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (371, 'Half-Corrupted Fusion Zamasu', 1, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (372, 'Super Saiyan God SS Vegito', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (373, 'Super Saiyan 2 Kefla', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (374, 'Super Saiyan 3 Gotenks', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (375, 'Super Saiyan Rosé Goku Black', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (376, 'Vegeta', 5, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (377, 'Goku', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (378, 'Super Saiyan Goku', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (379, 'Super Saiyan 2 Goku', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (380, 'Super Saiyan 3 Goku', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (381, 'Super Saiyan God Goku', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (382, 'Super Saiyan God SS Goku', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (383, 'Gohan (Kid)', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (384, 'Super Saiyan Trunks (Kid)', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (385, 'Super Saiyan Gohan (Youth)', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (386, 'Zangya', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (387, 'Boujack', 1, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (388, 'Super Saiyan Trunks (Teen)', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (389, 'Final Form Frieza: Full Power', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (390, 'Appule', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (391, 'Ramon', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (392, 'Orlen', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (393, 'Nabana', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (394, 'Roberry', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (395, 'Raspberry', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (396, 'Navel', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (397, 'Monrei', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (398, 'Guprei', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (399, 'Super Saiyan 3 Goku', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (400, 'Majuub', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (401, 'Super Saiyan Goku', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (402, 'Legendary Super Saiyan Broly', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (403, 'Super Saiyan God SS Evolved Vegeta', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (404, 'Jiren', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (405, 'God of Destruction Toppo', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (406, 'Super Saiyan 2 Caulifla: Kale (Assist)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (407, 'Perfect Cell', 5, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (408, 'Vegeta', 1, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (409, 'Yajirobe', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (410, 'Saibaman', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (411, 'Kaiwareman', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (412, 'Kyukonman', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (413, 'Tennenman', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (414, 'Jinkouman', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (415, 'Copyman', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (416, 'Gohan (Kid): Piccolo (Assist)', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (417, 'Super Saiyan 2 Gohan (Youth)', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (418, 'Omega Shenron', 1, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (419, 'Super Saiyan Goku', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (420, 'Fused with Nail Piccolo', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (421, 'Super Saiyan Rosé Goku Black', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (422, 'Super Saiyan God SS Goku & Vegeta', 5, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (423, 'Broly', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (424, 'Final Form Frieza', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (425, 'Super Saiyan Trunks (Adult)', 2, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (426, 'Zamasu: Goku Black (Assist)', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (427, 'Mai', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (428, 'Super Gogeta', 2, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (429, '1st Form Frieza', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (430, 'Bardock', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (431, 'Tora', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (432, 'Fasha', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (433, 'Kaioken Goku', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (434, 'Final Form Frieza', 2, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (435, 'Android #18', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (436, 'Jiren: Full Power', 5, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (437, 'God of Destruction Beerus', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (438, 'Toppo', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (439, 'Dyspo', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (440, 'Super Saiyan God SS Goku', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (441, 'Super Saiyan God SS Vegeta', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (442, 'Super Saiyan God SS Kaioken Goku', 4, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (443, 'Golden Frieza', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (444, 'Whis', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (445, 'Super Saiyan Trunks (Teen)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (446, 'Android #17 & Android #18', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (447, 'Gohan & Trunks (Youth)', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (448, 'Super Saiyan Gogeta', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (449, 'Gamma 1', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (450, 'Gamma 2', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (451, 'Ultra Instinct Goku', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (452, 'Super Saiyan Vegeta', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (453, 'Goku', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (454, 'Krillin', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (455, 'Tien', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (456, 'Super Saiyan 3 Goku', 3, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (457, 'Hero Tapion', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (458, 'Turles', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (459, 'Final Form Cooler', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (460, 'Majin Vegeta', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (461, 'Super Vegito', 4, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (462, 'Ultimate Gohan Absorbed Buu: Super', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (463, 'Tien', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (464, 'Perfect Form Cell', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (465, 'Beast Gohan', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (466, 'Power Awakening Piccolo', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (467, 'Metal Cooler', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (468, 'Final Form Cooler', 1, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (469, 'Legendary Super Saiyan Broly', 5, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (470, 'Thouser', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (471, 'Super Saiyan Trunks (Teen)', 3, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (472, 'Mecha Frieza', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (473, 'Goku Black', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (474, 'Pan', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (475, 'Super Saiyan 4 Goku & Vegeta', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (476, 'Android #17', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (477, 'Buu: Super', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (478, 'Super #17', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (479, 'Super Saiyan God SS Gogeta', 5, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (480, 'Android #18', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (481, 'Android #17', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (482, 'Hit', 1, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (483, 'Super Saiyan 2 & Super Saiyan God SS Trunks (Adult) & Vegeta', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (484, 'Zamasu', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (485, 'Fusion Zamasu', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (486, 'Super Saiyan God SS Goku', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (487, 'Super Saiyan God SS Vegeta', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (488, 'Super Saiyan Broly: Full Power', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (489, 'Omega Shenron', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (490, 'Majuub', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (491, 'Super Saiyan Goku', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (492, 'Giblet', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (493, 'Zahha', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (494, 'Saiyan in Red', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (495, 'Super Saiyan 2 Kefla', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (496, 'Super Saiyan God SS Goku', 3, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (497, 'Master Roshi', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (498, 'Bergamo', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (499, 'Super Saiyan Kale (Berserk)', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (500, 'Super Saiyan 2 Trunks (Adult)', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (501, 'Super Saiyan Rosé Goku Black', 3, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (502, 'Super Saiyan Trunks (Adult)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (503, '2nd Form Cell', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (504, 'Pui Pui', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (505, 'Super Saiyan 3 & Super Saiyan 2 Goku & Vegeta', 2, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (506, 'Buu: Kid', 4, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (507, 'Goku & Final Form Frieza', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (508, 'Jiren', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (509, 'Kahseral', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (510, 'Kyawei', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (511, 'God of Destruction Champa', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (512, 'Vados', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (513, 'Ultimate Gohan', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (514, 'Super Saiyan God SS Vegeta', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (515, 'Final Form Cooler', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (516, 'Android #13', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (517, 'Gamma 1 & Gamma 2', 4, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (518, 'Magenta', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (519, 'Power Awakening Piccolo', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (520, 'Gohan', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (521, 'Goku Black', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (522, 'Super Saiyan God SS Vegito', 1, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (523, 'Perfect Form Cell', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (524, 'Super Saiyan Gohan (Youth)', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (525, 'Cell Jr.', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (526, 'Android #18', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (527, 'Goku', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (528, 'Captain Ginyu', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (529, 'Jeice & Burter', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (530, 'Recoome & Guldo', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (531, 'Super Saiyan Goku', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (532, 'Gohan (Kid) & Krillin', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (533, 'Goku (Youth)', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (534, 'Android #8', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (535, 'Master Roshi', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (536, 'Goku', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (537, 'Piccolo Jr.', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (538, 'Demon King Piccolo', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (539, 'Hero Tapion', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (540, 'Super Janemba', 2, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (541, 'Pikkon', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (542, 'Metal Cooler', 4, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (543, 'Super Saiyan Gohan (Youth)', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (544, 'Super Saiyan God SS Evolved & Super Saiyan God SS Kaioken Vegeta & Goku', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (545, 'Golden Frieza', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (546, 'Cooler', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (547, 'Ultimate Gohan', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (548, 'Gotenks', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (549, 'Golden Frieza', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (550, 'Final Form Frieza', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (551, 'Goku & Bardock', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (552, 'Final Form Frieza', 1, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (553, 'Bardock', 5, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (554, 'Ultra Instinct -Sign- Goku', 4, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (555, 'God of Destruction Beerus', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (556, 'Goku', 2, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (557, 'Pan: Trunks & Giru (Assist)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (558, 'Trunks', 3, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (559, 'Whis', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (560, 'Bulla: Vegeta (Assist)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (561, 'Rage Shenron', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (562, 'Red Ribbon Army Piccolo', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (563, 'Super #17', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (564, '1st Form Cell', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (565, 'Super Vegeta', 1, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (566, 'Android #16', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (567, 'Super Saiyan 2 Gohan (Youth)', 3, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (568, 'Broly: Fury', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (569, 'Super Baby 2', 4, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (570, 'Trunks (Parasitism) Baby', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (571, 'Golden Frieza', 5, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (572, 'Raditz', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (573, 'Goku', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (574, 'Yamcha', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (575, 'Nappa', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (576, 'Super Saiyan God SS Goku & Vegeta', 4, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (577, 'Vegeta & Goku', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (578, 'Broly: Fury', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (579, 'East Supreme Kai Shin', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (580, 'Android #18', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (581, 'Bulma (Youth)', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (582, 'Super Saiyan God Goku', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (583, 'God of Destruction Beerus', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (584, 'Ultimate Gohan', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (585, 'Majin Buu: Pure Evil', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (586, 'Super Saiyan Trunks (Adult) (Rage)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (587, 'Syn Shenron', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (588, 'Super Saiyan 4 Gogeta', 5, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (589, 'Omega Shenron', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (590, 'Super Saiyan Goten (Kid)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (591, 'Super Saiyan Broly', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (592, 'Super Saiyan Goku', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (593, 'Videl', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (594, 'Jiren', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (595, 'Super Saiyan Gohan (Teen)', 2, 3, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (596, 'Piccolo & Goku', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (597, 'Garlic Jr.', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (598, 'Boujack', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (599, 'Goku', 4, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (600, 'Daiz', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (601, 'Amond', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (602, 'Cacao', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (603, 'Turles', 2, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (604, 'Rasin: Lakasei (Assist)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (605, 'Super Saiyan 3 Goku', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (606, 'Super Saiyan 3 Gotenks', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (607, 'Majin Buu (Good): Hercule (Assist)', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (608, 'Majin Vegeta', 4, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (609, 'Goku (Mini)', 3, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (610, 'Hyper Meta-Rilldo', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (611, 'Goku (Mini)', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (612, 'Glorio', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (613, 'Vegito', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (614, 'Mai', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (615, 'Goku Black', 4, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (616, 'Perfect Form & Final Form Cell & Frieza', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (617, 'Super Saiyan Trunks (Teen)', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (618, 'Vegeta', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (619, 'Super Saiyan 2 Goku', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (620, 'Videl', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (621, 'Super Saiyan Goku (Mini)', 1, 2, true, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (622, 'Tamagami Number Three', 5, 2, false, true);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (623, 'Beast Gohan', 4, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (624, 'Super Saiyan God SS Goku', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (625, 'Super Saiyan Goten (Kid)', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (626, 'Super Saiyan Gohan & Trunks (Youth)', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (627, 'Android #18', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (628, 'Fusion Zamasu', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (629, 'Android #17', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (630, 'Fused with Kami Piccolo', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (631, 'Super Saiyan Goku', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (632, 'Super Trunks', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (633, 'Perfect Cell', 1, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (634, '2nd Form Cell', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (635, 'Super Saiyan 3 Vegeta', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (636, 'Majin Kuu', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (637, 'Super Saiyan 4 Goku', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (638, 'Majin Duu', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (639, 'Cyborg Tao', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (640, 'Demon King Piccolo', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (641, 'Tambourine', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (642, 'Goku (Youth)', 4, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (643, 'Jackie Chun', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (644, 'Goku', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (645, 'Vegeta', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (646, 'Super Saiyan Goku', 4, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (647, 'Krillin', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (648, 'Jiren: Full Power', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (649, 'Ultra Instinct -Sign- Goku', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (650, 'Super Saiyan 2 Caulifla & Kale', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (651, 'Super Saiyan God SS Vegeta', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (652, 'Super Saiyan Cabba', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (653, 'Tien & Chiaotzu', 5, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (654, 'Nappa', 4, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (655, 'Final Form Frieza: Full Power', 3, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (656, '3rd Form Frieza', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (657, 'Super Saiyan 2 Kefla', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (658, 'Final Form Frost: Full Power', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (659, 'Metal Cooler', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (660, 'King Cold', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (661, 'Super Saiyan 4 Vegeta', 1, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (662, 'Super Saiyan 3 Goku', 5, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (663, 'Android #13', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (664, 'Android #14 & Android #15', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (665, 'Half-Corrupted Fusion Zamasu', 5, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (666, 'Goku', 3, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (667, 'Super Saiyan Gohan (Youth)', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (668, 'Goku & Vegeta', 3, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (669, 'Super Janemba', 4, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (670, 'Super Saiyan Gotenks', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (671, 'Super Saiyan 2 Gohan (Youth)', 2, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (672, 'Super Saiyan God Goku & Hit', 1, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (673, 'Super Full Power Saiyan 4 Goku', 3, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (674, 'Super Saiyan Goku', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (675, 'Super Saiyan 3 Vegeta (Mini)', 4, 2, true, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (676, 'Tamagami Number Two', 1, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (677, 'Ultimate Gohan Absorbed Buu: Super', 1, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (678, 'Super Saiyan God SS Goku & Vegeta', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (679, 'Mai', 2, 2, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (680, 'Super Saiyan Trunks (Adult)', 3, 1, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (681, 'Shallot', 6, 4, false, false);
INSERT INTO characters (char_id, name, type_id, rarity_id, is_ll, is_zenkai) VALUES (682, 'Shallot', 6, 2, false, false);
