-- tags inserts

INSERT INTO tags (tag_id, tag_name) VALUES (1, 'Son Family');
INSERT INTO tags (tag_id, tag_name) VALUES (2, 'Vegeta Clan');
INSERT INTO tags (tag_id, tag_name) VALUES (3, 'Super Warrior');
INSERT INTO tags (tag_id, tag_name) VALUES (4, 'Girls');
INSERT INTO tags (tag_id, tag_name) VALUES (5, 'Frieza Force');
INSERT INTO tags (tag_id, tag_name) VALUES (6, 'Ginyu Force');
INSERT INTO tags (tag_id, tag_name) VALUES (7, 'Saiyan');
INSERT INTO tags (tag_id, tag_name) VALUES (8, 'Hybrid Saiyan');
INSERT INTO tags (tag_id, tag_name) VALUES (9, 'Super Saiyan');
INSERT INTO tags (tag_id, tag_name) VALUES (10, 'Universe 2');
INSERT INTO tags (tag_id, tag_name) VALUES (11, 'Universe 4');
INSERT INTO tags (tag_id, tag_name) VALUES (12, 'Universe 6');
INSERT INTO tags (tag_id, tag_name) VALUES (13, 'Universe 9');
INSERT INTO tags (tag_id, tag_name) VALUES (14, 'Universe 11');
INSERT INTO tags (tag_id, tag_name) VALUES (15, 'Otherworld Warrior');
INSERT INTO tags (tag_id, tag_name) VALUES (16, 'Kids');
INSERT INTO tags (tag_id, tag_name) VALUES (17, 'Transforming Warrior');
INSERT INTO tags (tag_id, tag_name) VALUES (18, 'Android');
INSERT INTO tags (tag_id, tag_name) VALUES (19, 'Future');
INSERT INTO tags (tag_id, tag_name) VALUES (20, 'Angel');
INSERT INTO tags (tag_id, tag_name) VALUES (21, 'God of Destruction');
INSERT INTO tags (tag_id, tag_name) VALUES (22, 'Regeneration');
INSERT INTO tags (tag_id, tag_name) VALUES (23, 'GT');
INSERT INTO tags (tag_id, tag_name) VALUES (24, 'Merging');
INSERT INTO tags (tag_id, tag_name) VALUES (25, 'Fusion');
INSERT INTO tags (tag_id, tag_name) VALUES (26, 'Potara');
INSERT INTO tags (tag_id, tag_name) VALUES (27, 'Absorption');
INSERT INTO tags (tag_id, tag_name) VALUES (28, 'Twins');
INSERT INTO tags (tag_id, tag_name) VALUES (29, 'Super Saiyan 2');
INSERT INTO tags (tag_id, tag_name) VALUES (30, 'Fusion Warrior');
INSERT INTO tags (tag_id, tag_name) VALUES (31, 'God Ki');
INSERT INTO tags (tag_id, tag_name) VALUES (32, 'Super Saiyan 3');
INSERT INTO tags (tag_id, tag_name) VALUES (33, 'Lineage of Evil');
INSERT INTO tags (tag_id, tag_name) VALUES (34, 'Legends Road');
INSERT INTO tags (tag_id, tag_name) VALUES (35, 'Super Saiyan God');
INSERT INTO tags (tag_id, tag_name) VALUES (36, 'Super Saiyan God SS');
INSERT INTO tags (tag_id, tag_name) VALUES (37, 'Minion');
INSERT INTO tags (tag_id, tag_name) VALUES (38, 'Namekian');
INSERT INTO tags (tag_id, tag_name) VALUES (39, 'Super Saiyan 4');
INSERT INTO tags (tag_id, tag_name) VALUES (40, 'Super Saiyan Rosé');
INSERT INTO tags (tag_id, tag_name) VALUES (41, 'Team Bardock');
INSERT INTO tags (tag_id, tag_name) VALUES (42, 'Shadow Dragon');
INSERT INTO tags (tag_id, tag_name) VALUES (43, 'Powerful Opponent');
INSERT INTO tags (tag_id, tag_name) VALUES (44, 'Rival Universe');
INSERT INTO tags (tag_id, tag_name) VALUES (45, 'Hera Clan');
INSERT INTO tags (tag_id, tag_name) VALUES (46, 'Event Exclusive');
INSERT INTO tags (tag_id, tag_name) VALUES (47, 'Universe Rep');
INSERT INTO tags (tag_id, tag_name) VALUES (48, 'DB');
INSERT INTO tags (tag_id, tag_name) VALUES (49, 'Turles Crusher Corps');
INSERT INTO tags (tag_id, tag_name) VALUES (50, 'DAIMA');
INSERT INTO tags (tag_id, tag_name) VALUES (51, 'Weapon Wielder');
INSERT INTO tags (tag_id, tag_name) VALUES (52, 'Support Type');
INSERT INTO tags (tag_id, tag_name) VALUES (53, 'Defense Type');
INSERT INTO tags (tag_id, tag_name) VALUES (54, 'Melee Type');
INSERT INTO tags (tag_id, tag_name) VALUES (55, 'Ranged Type');
INSERT INTO tags (tag_id, tag_name) VALUES (56, 'Game Originals');
INSERT INTO tags (tag_id, tag_name) VALUES (57, 'Dragon Ball Saga');
INSERT INTO tags (tag_id, tag_name) VALUES (58, 'Saiyan Saga (Z)');
INSERT INTO tags (tag_id, tag_name) VALUES (59, 'Frieza Saga (Z)');
INSERT INTO tags (tag_id, tag_name) VALUES (60, 'Androids Saga (Z)');
INSERT INTO tags (tag_id, tag_name) VALUES (61, 'Cell Saga (Z)');
INSERT INTO tags (tag_id, tag_name) VALUES (62, 'Majin Buu Saga (Z)');
INSERT INTO tags (tag_id, tag_name) VALUES (63, 'Black Star Dragon Ball Saga (GT)');
INSERT INTO tags (tag_id, tag_name) VALUES (64, 'Super Baby Saga (GT)');
INSERT INTO tags (tag_id, tag_name) VALUES (65, 'Super #17 Saga (GT)');
INSERT INTO tags (tag_id, tag_name) VALUES (66, 'Shadow Dragon Saga (GT)');
INSERT INTO tags (tag_id, tag_name) VALUES (67, 'Frieza Resurrected Saga (S)');
INSERT INTO tags (tag_id, tag_name) VALUES (68, 'Anime Original Sagas');
INSERT INTO tags (tag_id, tag_name) VALUES (69, 'Sagas From the Movies');
INSERT INTO tags (tag_id, tag_name) VALUES (70, 'God of Destruction Champa Saga (S)');
INSERT INTO tags (tag_id, tag_name) VALUES (71, '"Future" Trunks Saga (S)');
INSERT INTO tags (tag_id, tag_name) VALUES (72, 'Universe Survival Saga (S)');
INSERT INTO tags (tag_id, tag_name) VALUES (73, 'God of Destruction Beerus Saga (S)');
INSERT INTO tags (tag_id, tag_name) VALUES (74, 'DRAGON BALL FighterZ');
INSERT INTO tags (tag_id, tag_name) VALUES (75, 'Dragon Ball Z: Kakarot');
INSERT INTO tags (tag_id, tag_name) VALUES (76, 'DAIMA Saga');
INSERT INTO tags (tag_id, tag_name) VALUES (77, 'DRAGON BALL 40th Anniversary');
INSERT INTO tags (tag_id, tag_name) VALUES (78, 'Sagas From the Movies (SUPER HERO)');
INSERT INTO tags (tag_id, tag_name) VALUES (79, 'Shallot');
INSERT INTO tags (tag_id, tag_name) VALUES (80, 'Giblet');
INSERT INTO tags (tag_id, tag_name) VALUES (81, 'Zahha');
INSERT INTO tags (tag_id, tag_name) VALUES (82, 'Goku');
INSERT INTO tags (tag_id, tag_name) VALUES (83, 'Gohan');
INSERT INTO tags (tag_id, tag_name) VALUES (84, 'Piccolo');
INSERT INTO tags (tag_id, tag_name) VALUES (85, 'Krillin');
INSERT INTO tags (tag_id, tag_name) VALUES (86, 'Yamcha');
INSERT INTO tags (tag_id, tag_name) VALUES (87, 'Tien');
INSERT INTO tags (tag_id, tag_name) VALUES (88, 'Chiaotzu');
INSERT INTO tags (tag_id, tag_name) VALUES (89, 'Raditz');
INSERT INTO tags (tag_id, tag_name) VALUES (90, 'Saibaman');
INSERT INTO tags (tag_id, tag_name) VALUES (91, 'Nappa');
INSERT INTO tags (tag_id, tag_name) VALUES (92, 'Vegeta');
INSERT INTO tags (tag_id, tag_name) VALUES (93, 'Zarbon');
INSERT INTO tags (tag_id, tag_name) VALUES (94, 'Dodoria');
INSERT INTO tags (tag_id, tag_name) VALUES (95, 'Guldo');
INSERT INTO tags (tag_id, tag_name) VALUES (96, 'Burter');
INSERT INTO tags (tag_id, tag_name) VALUES (97, 'Recoome');
INSERT INTO tags (tag_id, tag_name) VALUES (98, 'Jeice');
INSERT INTO tags (tag_id, tag_name) VALUES (99, 'Captain Ginyu');
INSERT INTO tags (tag_id, tag_name) VALUES (100, 'Frieza');
INSERT INTO tags (tag_id, tag_name) VALUES (101, 'Mercenary Tao');
INSERT INTO tags (tag_id, tag_name) VALUES (102, 'Pikkon');
INSERT INTO tags (tag_id, tag_name) VALUES (103, 'Jaco');
INSERT INTO tags (tag_id, tag_name) VALUES (104, 'Frost');
INSERT INTO tags (tag_id, tag_name) VALUES (105, 'Pan');
INSERT INTO tags (tag_id, tag_name) VALUES (106, 'Trunks');
INSERT INTO tags (tag_id, tag_name) VALUES (107, 'Android #20');
INSERT INTO tags (tag_id, tag_name) VALUES (108, 'Android #19');
INSERT INTO tags (tag_id, tag_name) VALUES (109, 'Turles');
INSERT INTO tags (tag_id, tag_name) VALUES (110, 'Mai');
INSERT INTO tags (tag_id, tag_name) VALUES (111, 'Android #17');
INSERT INTO tags (tag_id, tag_name) VALUES (112, 'Android #18');
INSERT INTO tags (tag_id, tag_name) VALUES (113, 'Cell');
INSERT INTO tags (tag_id, tag_name) VALUES (114, 'Master Roshi');
INSERT INTO tags (tag_id, tag_name) VALUES (115, 'Cabba');
INSERT INTO tags (tag_id, tag_name) VALUES (116, 'Bardock');
INSERT INTO tags (tag_id, tag_name) VALUES (117, 'Demon King Piccolo');
INSERT INTO tags (tag_id, tag_name) VALUES (118, 'Broly');
INSERT INTO tags (tag_id, tag_name) VALUES (119, 'Kaiwareman');
INSERT INTO tags (tag_id, tag_name) VALUES (120, 'Kyukonman');
INSERT INTO tags (tag_id, tag_name) VALUES (121, 'Copyman');
INSERT INTO tags (tag_id, tag_name) VALUES (122, 'Tennenman');
INSERT INTO tags (tag_id, tag_name) VALUES (123, 'Jinkouman');
INSERT INTO tags (tag_id, tag_name) VALUES (124, 'Nabana');
INSERT INTO tags (tag_id, tag_name) VALUES (125, 'Roberry');
INSERT INTO tags (tag_id, tag_name) VALUES (126, 'Appule');
INSERT INTO tags (tag_id, tag_name) VALUES (127, 'Ramon');
INSERT INTO tags (tag_id, tag_name) VALUES (128, 'Orlen');
INSERT INTO tags (tag_id, tag_name) VALUES (129, 'Raspberry');
INSERT INTO tags (tag_id, tag_name) VALUES (130, 'Navel');
INSERT INTO tags (tag_id, tag_name) VALUES (131, 'Monrei');
INSERT INTO tags (tag_id, tag_name) VALUES (132, 'Guprei');
INSERT INTO tags (tag_id, tag_name) VALUES (133, 'Android #16');
INSERT INTO tags (tag_id, tag_name) VALUES (134, 'Cooler');
INSERT INTO tags (tag_id, tag_name) VALUES (135, 'Thouser');
INSERT INTO tags (tag_id, tag_name) VALUES (136, 'Cell Jr.');
INSERT INTO tags (tag_id, tag_name) VALUES (137, 'Boujack');
INSERT INTO tags (tag_id, tag_name) VALUES (138, 'Caulifla');
INSERT INTO tags (tag_id, tag_name) VALUES (139, 'Zangya');
INSERT INTO tags (tag_id, tag_name) VALUES (140, 'Goku Black');
INSERT INTO tags (tag_id, tag_name) VALUES (141, 'Zamasu');
INSERT INTO tags (tag_id, tag_name) VALUES (142, 'Kale');
INSERT INTO tags (tag_id, tag_name) VALUES (143, 'Vegito');
INSERT INTO tags (tag_id, tag_name) VALUES (144, 'Goten');
INSERT INTO tags (tag_id, tag_name) VALUES (145, 'Hercule');
INSERT INTO tags (tag_id, tag_name) VALUES (146, 'Majin Buu');
INSERT INTO tags (tag_id, tag_name) VALUES (147, 'Gotenks');
INSERT INTO tags (tag_id, tag_name) VALUES (148, 'Dabura');
INSERT INTO tags (tag_id, tag_name) VALUES (149, 'Gogeta');
INSERT INTO tags (tag_id, tag_name) VALUES (150, 'Janemba');
INSERT INTO tags (tag_id, tag_name) VALUES (151, 'Chilled');
INSERT INTO tags (tag_id, tag_name) VALUES (152, 'Fasha');
INSERT INTO tags (tag_id, tag_name) VALUES (153, 'Tora');
INSERT INTO tags (tag_id, tag_name) VALUES (154, 'Saiyan in Red');
INSERT INTO tags (tag_id, tag_name) VALUES (155, 'Beerus');
INSERT INTO tags (tag_id, tag_name) VALUES (156, 'Whis');
INSERT INTO tags (tag_id, tag_name) VALUES (157, 'Ribrianne');
INSERT INTO tags (tag_id, tag_name) VALUES (158, 'Chi-Chi');
INSERT INTO tags (tag_id, tag_name) VALUES (159, 'Kakunsa');
INSERT INTO tags (tag_id, tag_name) VALUES (160, 'Rozie');
INSERT INTO tags (tag_id, tag_name) VALUES (161, 'Bulma');
INSERT INTO tags (tag_id, tag_name) VALUES (162, 'Lord Slug');
INSERT INTO tags (tag_id, tag_name) VALUES (163, 'Videl');
INSERT INTO tags (tag_id, tag_name) VALUES (164, 'Hyper Meta-Rilldo');
INSERT INTO tags (tag_id, tag_name) VALUES (165, 'Great Saiyaman 1');
INSERT INTO tags (tag_id, tag_name) VALUES (166, 'Great Saiyaman 2');
INSERT INTO tags (tag_id, tag_name) VALUES (167, 'Hit');
INSERT INTO tags (tag_id, tag_name) VALUES (168, 'Android #13');
INSERT INTO tags (tag_id, tag_name) VALUES (169, 'Android #14');
INSERT INTO tags (tag_id, tag_name) VALUES (170, 'Android #15');
INSERT INTO tags (tag_id, tag_name) VALUES (171, 'Nail');
INSERT INTO tags (tag_id, tag_name) VALUES (172, 'Shisami');
INSERT INTO tags (tag_id, tag_name) VALUES (173, 'Tapion');
INSERT INTO tags (tag_id, tag_name) VALUES (174, 'Syn Shenron');
INSERT INTO tags (tag_id, tag_name) VALUES (175, 'Nuova Shenron');
INSERT INTO tags (tag_id, tag_name) VALUES (176, 'Baby');
INSERT INTO tags (tag_id, tag_name) VALUES (177, 'Champa');
INSERT INTO tags (tag_id, tag_name) VALUES (178, 'Kefla');
INSERT INTO tags (tag_id, tag_name) VALUES (179, 'Bergamo');
INSERT INTO tags (tag_id, tag_name) VALUES (180, 'Lavender');
INSERT INTO tags (tag_id, tag_name) VALUES (181, 'Basil');
INSERT INTO tags (tag_id, tag_name) VALUES (182, 'Launch');
INSERT INTO tags (tag_id, tag_name) VALUES (183, 'Android #21');
INSERT INTO tags (tag_id, tag_name) VALUES (184, 'Shugesh');
INSERT INTO tags (tag_id, tag_name) VALUES (185, 'Borgos');
INSERT INTO tags (tag_id, tag_name) VALUES (186, 'Vados');
INSERT INTO tags (tag_id, tag_name) VALUES (187, 'Eis Shenron');
INSERT INTO tags (tag_id, tag_name) VALUES (188, 'Bido');
INSERT INTO tags (tag_id, tag_name) VALUES (189, 'Bujin');
INSERT INTO tags (tag_id, tag_name) VALUES (190, 'Gokua');
INSERT INTO tags (tag_id, tag_name) VALUES (191, 'Jiren');
INSERT INTO tags (tag_id, tag_name) VALUES (192, 'Toppo');
INSERT INTO tags (tag_id, tag_name) VALUES (193, 'Dyspo');
INSERT INTO tags (tag_id, tag_name) VALUES (194, 'Uub');
INSERT INTO tags (tag_id, tag_name) VALUES (195, 'Yajirobe');
INSERT INTO tags (tag_id, tag_name) VALUES (196, 'Yurin');
INSERT INTO tags (tag_id, tag_name) VALUES (197, 'Gamma 1');
INSERT INTO tags (tag_id, tag_name) VALUES (198, 'Gamma 2');
INSERT INTO tags (tag_id, tag_name) VALUES (199, 'Pui Pui');
INSERT INTO tags (tag_id, tag_name) VALUES (200, 'Kahseral');
INSERT INTO tags (tag_id, tag_name) VALUES (201, 'Kyawei');
INSERT INTO tags (tag_id, tag_name) VALUES (202, 'Magenta');
INSERT INTO tags (tag_id, tag_name) VALUES (203, 'Android #8');
INSERT INTO tags (tag_id, tag_name) VALUES (204, 'Rage Shenron');
INSERT INTO tags (tag_id, tag_name) VALUES (205, 'Bulla');
INSERT INTO tags (tag_id, tag_name) VALUES (206, 'Amond');
INSERT INTO tags (tag_id, tag_name) VALUES (207, 'Cacao');
INSERT INTO tags (tag_id, tag_name) VALUES (208, 'Shin');
INSERT INTO tags (tag_id, tag_name) VALUES (209, 'Daiz');
INSERT INTO tags (tag_id, tag_name) VALUES (210, 'Rasin');
INSERT INTO tags (tag_id, tag_name) VALUES (211, 'Garlic Jr.');
INSERT INTO tags (tag_id, tag_name) VALUES (212, 'Glorio');
INSERT INTO tags (tag_id, tag_name) VALUES (213, 'Tamagami Number Two');
INSERT INTO tags (tag_id, tag_name) VALUES (214, 'Tamagami Number Three');
INSERT INTO tags (tag_id, tag_name) VALUES (215, 'Majin Kuu');
INSERT INTO tags (tag_id, tag_name) VALUES (216, 'Majin Duu');
INSERT INTO tags (tag_id, tag_name) VALUES (217, 'Jackie Chun');
INSERT INTO tags (tag_id, tag_name) VALUES (218, 'King Cold');
INSERT INTO tags (tag_id, tag_name) VALUES (219, 'Special Cover Change (Strike)');
INSERT INTO tags (tag_id, tag_name) VALUES (220, 'Special Cover Change (Blast)');
INSERT INTO tags (tag_id, tag_name) VALUES (221, 'Special Cover Change (Strike/Blast)');
INSERT INTO tags (tag_id, tag_name) VALUES (222, 'Special Cover Change (Unique)');
INSERT INTO tags (tag_id, tag_name) VALUES (223, 'Reverse Element Factors');
INSERT INTO tags (tag_id, tag_name) VALUES (224, 'Endurance');
INSERT INTO tags (tag_id, tag_name) VALUES (225, 'Revive');
INSERT INTO tags (tag_id, tag_name) VALUES (226, 'Tag');
INSERT INTO tags (tag_id, tag_name) VALUES (227, 'Endurance Nullification');
INSERT INTO tags (tag_id, tag_name) VALUES (228, 'Element Switch');
INSERT INTO tags (tag_id, tag_name) VALUES (229, 'Revive (Chance)');
INSERT INTO tags (tag_id, tag_name) VALUES (230, 'Succession');
INSERT INTO tags (tag_id, tag_name) VALUES (231, 'Summon Backup');
INSERT INTO tags (tag_id, tag_name) VALUES (232, 'Wide-Range Special Arts');
INSERT INTO tags (tag_id, tag_name) VALUES (233, 'Nullify wide-range Special Arts');
INSERT INTO tags (tag_id, tag_name) VALUES (234, 'Revive Nullified');
INSERT INTO tags (tag_id, tag_name) VALUES (235, 'Ultra Instinct');
INSERT INTO tags (tag_id, tag_name) VALUES (236, 'Final Counter');
INSERT INTO tags (tag_id, tag_name) VALUES (237, 'RR Disrupt');
INSERT INTO tags (tag_id, tag_name) VALUES (238, 'Time Skip');
INSERT INTO tags (tag_id, tag_name) VALUES (239, 'Character Sealing');
INSERT INTO tags (tag_id, tag_name) VALUES (240, 'Rising Rush Counter');
INSERT INTO tags (tag_id, tag_name) VALUES (241, 'Arts Action');
INSERT INTO tags (tag_id, tag_name) VALUES (242, 'Indestructible');
INSERT INTO tags (tag_id, tag_name) VALUES (243, 'Cover Change Prevention');
INSERT INTO tags (tag_id, tag_name) VALUES (244, 'Comeback');
INSERT INTO tags (tag_id, tag_name) VALUES (245, 'Assault Chain');
INSERT INTO tags (tag_id, tag_name) VALUES (246, 'RR Defeat Nullification');
INSERT INTO tags (tag_id, tag_name) VALUES (247, 'Synchro Gauge');
INSERT INTO tags (tag_id, tag_name) VALUES (248, 'Active Gauge');
INSERT INTO tags (tag_id, tag_name) VALUES (249, 'KO Guard');
INSERT INTO tags (tag_id, tag_name) VALUES (250, 'Switch Attack');
INSERT INTO tags (tag_id, tag_name) VALUES (251, 'Anti-Cover Change Attack');
